### ISSUE TITLE
PMODE/W

### ISSUE THREAD

**Issue by vii1** [vii1/DIV#12]
El DIV original usaba PMODE/W como sustituto de DOS/4GW. Estaría bien hacer un script o algo para ejecutarlo automáticamente con DOSBOX e incorporarlo en los makefiles.

**Comment by vii1** [comment]
Definitivamente el IDE usa DOS/4GW. Probablemente PMODE/W era para la DIV32RUN.DLL, para evitar que los juegos tuviesen una dependencia más. Investigaré.

**Comment by vii1** [comment]
Leyendo la documentación de PMODE/W extraigo las siguientes características:
* Compatibilidad con DOS/4GW
* Mucho más compacto (~11 KB en vez de los ~250 KB de DOS/4GW)
* Runtime incorporado en el propio stub
* Permite comprimir el EXE (con la utilidad PMWLITE)
* Gratuito para uso no comercial, en un sentido muy liberal (si el binario se puede descargar gratuitamente de Internet, ya entra en el concepto de uso no comercial de PMODE/W).
Todas estas características lo hacen ideal para la DIV32RUN.DLL, y el último punto prácticamente me lo confirma ya que DIV32RUN.DLL se podía descargar gratuitamente y estaba concebida para ser un runtime libremente distribuible.

**Comment by vii1** [comment]
También el binario del instalador (INSTALL.OVL) utiliza PMODE/W con PMWLITE.

**Comment by Zardoz89** [comment]
¿Y el [DOS/32](https://en.wikipedia.org/wiki/DOS/32) ? Ee compatible con el DOS/4GW y el PMODE/W y esta liberado el código.

**Comment by vii1** [comment]
Muy interesante, merece la pena considerarlo.

**Comment by vii1** [comment]
He creado una issue de mejora (#45) para DOS/32A y cierro esta, porque ya usamos PMODE/W para la div32run.
