### ISSUE TITLE
Mejorar instrucciones de compilación

### ISSUE THREAD

**Issue by Zardoz89** [vii1/DIV#29]
Relacionada con #7

Cosas que he notado al intentar compilar con el OpenWatcom 1.9 para DOS

- Es necesario tanto el compilador de 16 bit como el del 32. No basta solo con el compilador de 32 bit.
- El wstub no se compila (da error). Hay que meterse en el subidrectorio y lanzar el wmake
- El makefile no genera el directorio de salida, y el error que aparece no es evidente que falta dicho directorio. Habria que hacer que genere el directorio vacio para que no fale la compilación.

**Comment by vii1** [comment]
Hecho!
