### ISSUE TITLE
Modos de vídeo inestables

### ISSUE THREAD

**Issue by vii1** [vii1/DIV#32]
Al no encontrar un SVGAkit de la versión que usaba DIV acabé usando una versión más moderna, que cambia un poco la interfaz de la librería.
Adapté `v.cpp` y `divvideo.cpp` a la nueva versión pero puede que haga falta algo más. DIV tiene algunos modos hardcoded (sospecho que 320x200 y los modos-x).
En mis pruebas 320x200 y los modos VESA iban bien, pero los modos-x hacían que el IDE entrara en un loop infinito intentando probar el modo.

**Comment by vii1** [comment]
```c
void memcpyb(byte * d, byte * s, int n) {
  memcpy(d,s,n);
  compilar();
}
```

EXPEDIENTE X

**Comment by Zardoz89** [comment]
WTF?
