### ISSUE TITLE
Compilar las DLLs

### ISSUE THREAD

**Issue by vii1** [vii1/DIV#47]
Ahora mismo `wmake install` copia el código fuente de las DLLs al directorio DLL, pero `wmake` debería compilar las DLLs propiamente dichas y copiar los binarios en DLL y los fuentes en DLL/SOURCE.

**Comment by Zardoz89** [comment]
No me furula las DLLs. He compilado de la misma forma que lo hacia para el DIV2 original pero usando el open watcom 1.9 de linux (el mismo con el que compilo DIV). 

Cuando intenta compilar código que llama a funcionas de la DLL (he probado con mi csv.dll), compila bien. Lo cual sugiere que encuentra y ejecuta las funciones `div_main` y `div_library`. Si no fuese así, aparecería un error al compilar y encontrar un función que no reconoce. Sin embargo, cuando ejecuto el juego, peta al llamar a la función de la DLL.

En el DOSBOX aparece esto :
```
llegal read from 92139190, CS:IP      160:  218494
Illegal write to 92139190, CS:IP      160:  218494
```

La dll compilada está en https://github.com/Zardoz89/csvDll/tree/master/dist/viiDiv
A raiz de los problemas que tuve con DIV DX, las funciones `div_main` y `div_library`, así como las funciones que implemento, tienen un `extern "C"` . He comprobado en la versión original de DIV2, esto no da problemas y traga bien con la DLL.

**Comment by vii1** [comment]
@Zardoz89 prueba ahora. Con el último commit 26bdd134ba4dc8f7d00920ff9315f265a8411db8 ya deberían cargar correctamente tanto las DLLs nuevas como las originales compiladas con Watcom 10.x. Había varios problemas:
- No se tenía en cuenta el campo VirtualSize de las secciones del PE
- No se alineaba el tamaño de dichas secciones (no he visto por ninguna parte que fuese un requisito, pero la relocalización podía fallar si no se hacía así)
- DIV2 hacía un memset a cero de todas las secciones. Yo lo quité por innecesario, pero resulta que Watcom 10 espera que las secciones BSS (datos no inicializados) estén a cero igualmente.

Al menos esto ha servido para dar un buen lavado de cara al cargador de DLLs y desduplicar bastante código. Yay!

Ah, y he incluido una utilidad en `src/testdll` para probar que una DLL carga correctamente sin tener que arrancarla desde DIV.

**Comment by Zardoz89** [comment]
¡Funciona!
De hecho, mi mata-marcianos carga y funciona, salvo por los disparos que hace algo raro.
